{
 "title": "Homework-8",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "App latency 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "App latency 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "App latency 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "App latency max quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (uri, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "App Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\", uri=~\"/api/v1/user/\\\\{id\\\\}|/api/v1/users\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Nginx latency 0.5 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_request_size_bucket{ingress=\"usersformetrics-app\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Nginx latency 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_size_bucket{ingress=\"usersformetrics-app\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Nginx latency 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_size_bucket{ingress=\"usersformetrics-app\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Nginx latency max quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le)(rate(nginx_ingress_controller_request_size_bucket{ingress=\"usersformetrics-app\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_size_count{ingress=\"usersformetrics-app\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_request_size_count{status=\"500\", ingress=\"usersformetrics-app\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}