spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:catalogdb
    initialization-mode: always
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2.console.enabled: true

spring.cloud.stream:
  function:
    definition: catalogProcessor
  bindings:
    catalogProcessor-in-0:
      destination: order-event
    catalogProcessor-out-0:
      destination: catalog-event

server:
  port: 8092