spring:
  data:
    mongodb:
      port: 27017
      database: logistics

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - com.christinagorina.logistics.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

spring.cloud.stream:
  function:
    definition: catalogReservedConsumer;logisticsSupplier;
  bindings:
    catalogReservedConsumer-in-0:
      destination: catalog-reserved
    logisticsSupplier-out-0:
      destination: logistics-reserved
  kafka:
    bindings:
      catalogReservedConsumer-in-0:
        consumer:
          ack-mode: manual-immediate
        producer:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.UUIDSerializer


server:
  port: 8093
