---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: finalwork-namespace
  labels:
    app: catalog-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-final:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: finalwork-namespace
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 80
      name: http
      targetPort: 8092