spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:orderdb

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2.console.enabled: true

spring.cloud.stream:
  function:
    definition: orderSupplier
  bindings:
    catalogConsumer-in-0:
      destination: catalog-event
    orderSupplier-out-0:
      destination: order-event


server:
  port: 8091



